name: Continuous Integration

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJs [v16]
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g yarn jest
          yarn install

      - name: Checks for known security issues with the installed packages
        run: |
          yarn audit --groups dependencies

      - name: Run Unit tests with Coverage
        run: |
          yarn test:cov

      - name: Run End-to-End tests
        run: |
          yarn test:e2e

      - name: Environment Teardown
        if: always()
        run: |
          echo "Finished!"
