name: Continuous Integration

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/workflows/mutation-testing.yml'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJs [v18]
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g yarn jest
          yarn --ignore-scripts

      - name: Checks for known security issues with the installed packages
        run: |
          yarn audit --groups dependencies

      - name: Run Unit tests with Coverage
        run: |
          yarn test:cov

      - name: Run End-to-End tests
        run: |
          yarn test:e2e

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Environment Teardown
        if: always()
        run: |
          echo "Finished!"
