name: Mutation Tests

on:
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  mutation-tests:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Setup NodeJs [v16]
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g yarn jest stryker-cli
          yarn install

      - name: Checks for known security issues with the installed packages
        run: |
          yarn audit --groups dependencies

      - name: Run Mutation Tests
        run: |
          yarn test:mutation

      - name: Publish Mutation Reports
        run: |
          mkdir -p ./docs/mutation-report
          mv ./reports/mutation/mutation.html ./docs/mutation-report/index.html

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "SHOULD_I_COMMIT=Yes" >> $GITHUB_ENV
          else
            echo "SHOULD_I_COMMIT=No" >> $GITHUB_ENV
          fi

      - name: Commit the changes
        if: ${{ env.SHOULD_I_COMMIT == 'Yes' }}
        run: |
          git config pull.rebase false
          git config --local user.email "action@github.com"
          git config --local user.name "Stryker.NET"
          git add --all
          git commit -m "doc(testing): update mutation reports"
          git pull origin main

      - name: Push the changes
        if: ${{ env.SHOULD_I_COMMIT == 'Yes' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Environment Teardown
        if: always()
        run: |
          echo "Finished!"
